CREATE TABLE Courses (
  COURSE_CODE varchar(10) NOT NULL,
  COURSE_NAME varchar(20) DEFAULT NULL,
  CREDIT_HOURS varchar(20) DEFAULT NULL,
  ROLL_NO varchar(10) NOT NULL,
  PRIMARY KEY (COURSE_CODE),
  FOREIGN KEY (ROLL_NO) REFERENCES student(ROLL_NO) ON DELETE CASCADE
);




